version: '2'
services:
  db:
    restart: always
    image: postgres:latest
    container_name: backend-db
    mem_limit: 300m
    # mem_limit: 3g
    # memswap_limit: 6g
    environment:
      POSTGRES_DB: wb-parser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PZdlxEGhBbquka234Ylink12
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: 'postgres -c max_connections=9999'
    networks:
      backend:
        ipv4_address: 192.168.1.2
    logging:
      driver: 'json-file'
      options:
        max-file: '2'
        max-size: 750m
  redis:
    restart: always
    image: marketguru/redis:latest
    container_name: redis
    mem_limit: 100m
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      backend:
        ipv4_address: 192.168.1.3
    logging:
      driver: 'json-file'
      options:
        max-file: '2'
        max-size: 750m
networks:
  backend:
    external:
      name: backend
volumes:
  postgres-data:
    external:
      name: postgres-data
  redis-data:
    external:
      name: redis-data